### ISSUE TITLE
update to 2.1 broke data

### ISSUE THREAD

**Issue by HumanG33k** [scoute-dich/QuitSmoking#13]
Hello.

I just update to 2.1 from fdroid.
And after start my data are reset to 1970 years.
Any way to retrieve old files ?

**Comment by scoute-dich** [comment]
That's because of the new implementation of the date picker. The start time is now saved as a long value. Therefore it was saved as a string. You can simply enter the right start time in the settings. Than the correct values should be there again. The diary should not be affected.

Sorry for the discomfort.

I hope you get your data back.

Regards
Gaukler Faun

**Comment by HumanG33k** [comment]
can i retrieve it somewhere ?

**Comment by scoute-dich** [comment]
No. There aren't any files stored anywhere (except you made a backup of your diary, then you can restore your diary from the menu). As said, to get the correct time back you have to enter simply the correct time, when you stopped smoking in the settings.
