### ISSUE TITLE
[Feature request] Italian translation

### ISSUE THREAD

**Issue by Fernandus91** [scoute-dich/QuitSmoking#29]
Hi, I've been using this app for a few days. It is pretty amazing and well done and I also think that localization can help it to grow. I am Italian, so I can translate in that language, but I am not a developer; could anyone tell me where to find the wordsheet? Thanks.

**Comment by issueseverywhere** [comment]
Taking example fom the french translation, i think you can download and modify this, translating french to italian:
https://github.com/scoute-dich/QuitSmoking/blob/a70ac111604b94e6bcdecf650a3f65449216b959/app/src/main/res/values-fr/strings.xml

Or german to italian:
https://github.com/scoute-dich/QuitSmoking/blob/a70ac111604b94e6bcdecf650a3f65449216b959/app/src/main/res/values-de/strings.xml


-------- Courriel d’origine --------
De : Fernandus91 <notifications@github.com>
Envoyé : 28 décembre 2018 17:22:39 GMT+00:00
À : scoute-dich/QuitSmoking <QuitSmoking@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [scoute-dich/QuitSmoking] [Feature request] Italian translation (#29)

Hi, I've been using this app for a few days. It is pretty amazing and well done and I also think that localization can help it to grow. I am Italian, so I can translate in that language, but I am not a developer; could anyone tell me where to find the wordsheet? Thanks.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/scoute-dich/QuitSmoking/issues/29
